### ISSUE TITLE
Third-Party Integration Question

### ISSUE THREAD

**Issue by antjebara** [github/SoftU2F#13]
Hello,
Amazing Project! 

I'm the Co-Founder of Myki (https://myki.co) and we just released the Myki Password Manager & Authenticator.

In our opinion, cloud storage of passwords, keys and certificates is convenient but constitutes a big security issue. Hackers shouldn't be able to compromise a publicly accessible server and as a result gain access to users credentials.

Myki follows a different approach by creating a private cloud in your pocket. All of your passwords and keys are securely encrypted on your smartphone (secure backups are automatically made on other devices that you own in an ad-hoc manner).

You can pair the Myki app with your computer browser by scanning a symmetrical encryption key (AES256 PBKDF2) generated by the browser extension.

This create an encrypted P2P connection between your phone and your browser.

When you need to login to an account on your computer, you receive a push notification to your smartphone. You can grant access from your mobile lock screen by using your fingerprint or a pin code.

The passwords are then encrypted with the shared key (generated by the browser) and sent to the browser extension that decrypts them and injects them in the website.

As a result of our unique architecture:
- Our servers are only used as relay servers (they don't hold any sensitive information, we can't get subpoenaed, if our servers are compromised they don't hold sensitive users' data)
- No master password needed (another password to secure all other passwords? Really?!)
- Myki can pair and log you in on an unlimited number of computers.
- Myki stores and auto-fills two-factor authentication tokens. (!important for the next part)
- Myki can remotely log you out of any account on your computer from the myki app on your phone

We would like to use the Keychain of the iPhone (and Android) to sign the request and relay it to your Mac app.

So the way it would work is as follows:
- You login to Github the regular way
- Github requests the u2f token
- The Mac app relays the request to the Myki mobile app/
- The user uses the Authenticator in his phone (the myki app) to verify his presence and sign the challenge..
- The info is sent back to the Mac app (e2e encrypted channel [AES256-CBC Key Shared by QR code])
- The Mac app emulates the HID device and sends the requested info to the browser.

Question: 
~ Do you think that it would somehow reduce the risks that you mentioned in your post? [Myki Mobile app acts as the U2F USB Device]
~ Do you agree that it would increase the usability by allowing you to use it on many computers?
~ (Technical question) The softu2f kernel extension. How do we get the authority to load it? I don't fully understand how it works etc.. if you could shed some light on the subject it would be amazing. [Assume 0 knowledge of how kernel extensions work]

Thank you 💃

**Comment by btoews** [comment]
Hey! Thanks for opening this. Myki sounds like a really cool app.

I'm really into the idea of storing key material on a separate device. The way I've envisioned this working in the past is to implement a [BTLE U2F](https://fidoalliance.org/specs/fido-u2f-v1.1-id-20160915/fido-u2f-bt-protocol-v1.1-id-20160915.html) authenticator on the phone which can communicate with your browser on your computer. I started working on this a while back [over here](https://github.com/mastahyeti/SecurityKeyBLE).

The problem I ran into was that none of the browsers implemented support for U2F over BTLE. I think it would be really cool to write a BTLE U2F "bridge" that uses the HID emulator from Soft U2F to allow a BTLE authenticator to work with browsers that only support HID U2F. If a few BTLE authenticators became available, browser vendors might feel more compelled to add support for BTLE U2F, obviating the need for the bridge.

So, how would this work with Myki? Instead of communicating authentication/registration requests over a proprietary protocol, I think Myki should implement a BTLE U2F authentication. That way, as browsers add support for BTLE U2F, your authenticator would work with them out of the box instead of requiring the user to install a kext. Again, a bunch of the work for such an app is already written [here](https://github.com/mastahyeti/SecurityKeyBLE).

> ~ Do you think that it would somehow reduce the risks that you mentioned in your post? [Myki Mobile app acts as the U2F USB Device]

Definitely!

> ~ Do you agree that it would increase the usability by allowing you to use it on many computers?

Yes.

> ~ (Technical question) The softu2f kernel extension. How do we get the authority to load it? I don't fully understand how it works etc.. if you could shed some light on the subject it would be amazing. [Assume 0 knowledge of how kernel extensions work]

So, macOS will refuse to load any kernel extension that isn't signed with a special certificate. You can request one of these certs [here](https://developer.apple.com/contact/kext/), but it is a real pain in the ass. It took me ~6 months to get one. Your best bet would be to take the `.kext` I'm publishing with Soft U2F and publish that with whatever app you're distributing.

**Comment by btoews** [comment]
I'm going to close this issue, but feel free to keep the conversation going here or via email if you'd rather.

**Comment by antjebara** [comment]
We replaced the Keychain signing part with Myki signing and replaced the notification popup function with a call to the user.

Check it out: [Myki Soft U2F Authentication](https://youtu.be/Xd4NsYFIFKg)

I think that there's still a lot of room for improvement.

We've been thinking of implementing UAF for a while but seeing that this is super cool and can be actually useful in 2017 we're now thinking of implementing BTLE U2F as you suggested.

~ What possible issues do you think that we'll run into?
~ I think that browsers implementing BTLE U2F will take a long time. The "bridge" seems like the short term solution. What do you suggest as next steps to achieve a universal bridge that can be used with any authenticator implementation?

**Comment by btoews** [comment]
Wow! That was fast :smile: 

Is the computer-side of Myki implemented as a standalone app or as a browser extension? I would love to add the BTLE "bridge" as a feature of Soft U2F. If you're already distributing a standalone app it might make more sense to add the feature there though. 

> ~ What possible issues do you think that we'll run into?

I can't think of any obvious hurdles, but I'm sure there will be some.

> ~ I think that browsers implementing BTLE U2F will take a long time. The "bridge" seems like the short term solution.

I actually started writing a Chrome patch a while back and it didn't seem like the change would be too difficult. I also think the folks on the Chrome team working on U2F/webauthn would be receptive to such a patch. [Here's](https://github.com/mastahyeti/chrome-ble-u2f-app) some of that work, though I honestly don't remember how far along it was. [Here's](https://bugs.chromium.org/p/chromium/issues/detail?id=649021&q=ble%20u2f&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified) a bug I opened on Chromium.

> What do you suggest as next steps to achieve a universal bridge that can be used with any authenticator implementation?

I'd read the BLE U2F spec and maybe try to resurrect or rewrite my SecurityKeyBLE project. I wrote both sides of the BLE stack and I think [this](https://github.com/mastahyeti/SecurityKeyBLE/blob/master/SecurityKeyBLEClient/SecurityKeyClient.swift) is the part that the bridge would use. From there, you could incorporate the BLE client into Myki, Soft U2F, or make a whole new app...

**Comment by yusef-ho** [comment]
@avvj hello, is the feature from youtube video you posted supported in Myki now??

**Comment by yackermann** [comment]
@avvj We are doing seminar on FIDO protocols at the bay. https://fidoalliance.org/events/silicon-valley-seminar/ and its free.

So if you want to talk about UAF/U2F/FIDO2/WebAuthn you might wanna come*)
