### ISSUE TITLE
Installer fails on missing folder.

### ISSUE THREAD

**Issue by opsroller** [github/SoftU2F#30]
When running the .pkg file the installer fails without a good message. I opened the console and searched for u2f and found " (com.apple.xpc.launchd.user.domain.501.100006.Aqua): Could not read path: path = /Users/${USER}/Library/LaunchAgents/com.github.SoftU2F.plist, error = 2: No such file or directory". Simple doing mkdir fixed the issue and the installer then succeeded.

**Comment by btoews** [comment]
You're the second person to run into this (https://github.com/github/SoftU2F/issues/22). This directory should exist on a fresh macOS install, so I'm curious what is causing it to be missing. Since this has affected multiple people, we can add something to the postinstall script to ensure that the directory exists.

**Comment by btoews** [comment]
#31 fixed this.
