### ISSUE TITLE
Doesn't work with webauthn

### ISSUE THREAD

**Issue by btoews** [github/SoftU2F#51]
Both Firefox and Chrome abort the webauthn transaction if the browser loses focus at any point. Because SoftU2F uses macOS notification prompts for test-of-user-presence, the browser must lose focus temporarily, though we return focus as quickly as possible. 

[This](https://bugzilla.mozilla.org/show_bug.cgi?format=default&id=1448408) is the Firefox bug. [This](https://bugs.chromium.org/p/chromium/issues/detail?id=750294#c_ts1518543361) Chrome bug is related, but I need to open something more specifically about this.

**Comment by wrinkledcheese** [comment]
Is this not intended behaviour?  https://www.w3.org/TR/webauthn/#abortoperation 

I read that as: When authenticating - DiscoverFromExternalSource - or registering - Create - if the Window object loses focus, then the operation must be aborted.

It seems like there would have to be hardware support on the OS in order to integrate WebAuthn via TEE, SE, or TPM, all of which are hardware solutions.  Intel and AMD have them in their processors, but I can't find exact dates with a cursory Google for Intel*, but AMD support started around 2013.  If that date holds true, only the newest desktops from Apple would have support in the processor, but may support it alternatively via TPM instead of TEE.

I would like to create a Linux version of what you've created here as well as a server in either C++, or Python.

'*' - This whitepaper suggests 2012, so probably only the latest Apple desktops as well.  I'm not sure how a virtual USB may integrate into these, but a physical USB would implement it's own hardware SE.
https://www.intel.com/content/www/us/en/architecture-and-technology/trusted-execution-technology/trusted-execution-technology-security-paper.html

**Comment by btoews** [comment]
Yep. The browsers are following the spec.

**Comment by mitsuhiko** [comment]
Does anyone have a known workaround for this issue with Firefox?

**Comment by yackermann** [comment]
@mitsuhiko Not at that moment. AFAIK they are still working to resolve it.

**Comment by qmnl** [comment]
**EDIT**: The following is a workaround. **Don't use it for any real site**. Better don't use it at all.

You can clone this repo, open it with XCode, let XCode fix the provisioning profiles (automatic signing), and set `static var skip = true`, and run the app through XCode. Then all request will automatically be accepted.

EDIT: You can try to implement for example a global keyboard shortcut instead of the notification. Then the browser won't loose focus.

**Comment by yackermann** [comment]
@simonmeusel This is a really bad idea. There are always must be TUP!

**Comment by qmnl** [comment]
If you only use it for developing your own site in a testing environment, it is perfect. It's a workaround.

But you should not use it for any real site indeed.

What is `TUP`?

**Comment by mitsuhiko** [comment]
TUP is test of user presence. For testing U2F you don't need this project anyways.

**Comment by qmnl** [comment]
What projects should I use?

But anyway it is the starting point, from where on you could for example implement keyboard shortcuts for TUP.

**Comment by yackermann** [comment]
BTW: @simonmeusel. There is a builtin FIDO2 authenticator in google chrome, and virtual U2F authenticator in Firefox

**Comment by mdempsky** [comment]
[Disclaimer: I don't use macOS and so have never used SoftU2F; I'm just looking into it as a recommendation to non-technical friends.]

Instead of requiring a mouse click as the TUP, could you register a global keyboard shortcut? That way the popup dialog doesn't need focus?

Does this affect keys that are protected with Touch ID too?

**Comment by btoews** [comment]
TUP is important, though it is arguably less important than it used to be, since browsers have added chrome to prompt users during webauthn flows. A global keyboard shortcut would be technically possible, but I think this would be a bad experience for users.

**Comment by imax9000** [comment]
Is there any decision on what needs to happen for SoftU2F to work in Firefox?

**Comment by btoews** [comment]
Firefox would have to be made more lax about losing focus during a webauthn flow.

**Comment by Ajedi32** [comment]
Could this be solved by saving the fact that the user clicked "Yes", prompting them to re-trigger the authentication prompt on the website, then immediately accepting next time the website asks? Not an _ideal_ user experience, but it would at least make it _possible_ to use SoftU2F with WebAuthn.

**Comment by btoews** [comment]
Yes, that would work, and yes, the UX wouldn't be ideal. I'm curious though why people aren't just using the new platform webauthn authenticator built into Chrome?

**Comment by Ajedi32** [comment]
I didn't realize Chrome had that feature; I can't seem to get it to work for me on https://webauthn.io/ anyway...

Even so, I'm more interested in getting WebAuthn to work with synchronized credentials for usability reasons, so a platform authentication that ties your identity to a specific device wouldn't work for me.

**Comment by btoews** [comment]
> I didn't realize Chrome had that feature; I can't seem to get it to work for me on https://webauthn.io/ anyway...

I just tried it for the first time and it worked on my MacBook with TouchID.

> Even so, I'm more interested in getting WebAuthn to work with synchronized credentials for usability reasons, so a platform authentication that ties your identity to a specific device wouldn't work for me.

For what it's worth, the macOS keychain doesn't allow for syncing the type of keychain entries used by SoftU2F. This means that SoftU2F is a platform authenticator to the same extent that Chrome's TouchID keys are.

I'm hoping that platform authenticators will start allowing for key syncing once more people start using WebAuthn. This will make the recovery flow and the flow for mobile devices much better.

**Comment by Ajedi32** [comment]
I'm on Windows right now so that might be why. Or perhaps it only works if your computer has a TPM and mine doesn't.

In any case, part of reason I'm interested in software authenticators is that those don't necessarily have to wait for the underlying platform to support key syncing in order to implement it (though I guess SoftU2F does if it uses the platform keychain under the hood).

Syncing isn't just important for account recovery, but also for account setup. Having to register every device manually before you can use it to sign-in is too much friction IMO if we want WebAuthn to replace passwords. Users need to be able to create an account on mobile, then effortlessly sign into that same account on desktop without having to perform any additional steps. And that needs to be true even if the user loses access to their phone after creating their account.

It's fine if SoftU2F doesn't want to support that; I just wanted to be sure that its _possible_ to implement a reasonably user-friendly software-based WebAuthn authenticator on current browsers. It's good to know the issues with browser focus aren't a _complete_ blocker.

**Comment by btoews** [comment]
> I'm on Windows right now so that might be why. 

SoftU2F is also macOS only. I agree though that key syncing would be nice.

**Comment by btoews** [comment]
It seems that this works on Chrome now. FF will also be changing their behavior as per [this comment](https://bugzilla.mozilla.org/show_bug.cgi?id=1448408#c7).
